### PR TITLE
Use https://rubygems.org 

### PR DESCRIPTION
**Pull request by etagwerker**
Hey @drewtempelmeyer, 

This PR upgrades the savon dependency. 

Please check it out.

Thanks!

### CODE REVIEW

**Comment by dblock** [comment]
Is the newer Savon version required? I mean does it not work with any 2.x?

**Comment by etagwerker** [comment]
@dblock Is there any reason to keep the dependency at >= 2.0 and not >= 2.11?

**Comment by dblock** [comment]
Because someone may be using an older version of Savon. You want the most relaxed dependency, ideally without even a version unless you have to. The reason it was >= 2.0 is because at some point it stopped being compatible with savon < 2.

**Comment by etagwerker** [comment]
@dblock Good point. I've updated this PR.

`bundle-audit` complains about the `http://` in the Gemfile, so I've made it point to `https://`

**Comment by drewtempelmeyer** [comment]
@etagwerker thanks for doing this!

**Pull request merged**
